<!DOCTYPE HTML>
<%@page import="com.dsce.pojo.Patient"%>
<%@page import="java.util.List"%>
<html>
<head>
<title>DSCE</title>
<%@include file="resources.jsp"%>
</head>
<body id="pageBody">
	<div id="divBoxed" class="container">

		<div class="transparent-bg"
			style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; z-index: -1; zoom: 1;"></div>

		<div class="divPanel notop nobottom">

			<%@include file="header.jsp"%>


		</div>

		<div class="contentArea">


			<div class="divPanel notop page-content">
				<a href='patientList'> <i class="general foundicon-left-arrow">
						Go Back </i>
				</a>
				<div class="page-header">
					<h1>Create a New Patient Record</h1>
				</div>


				<%
					String chk = (String) request.getAttribute("access");
					String chk2 = request.getParameter("write");
				%>
				<%
					if (chk != null && chk.equals("no")) {
				%>

				<div class='alert alert-error'>
					<i class="general foundicon-remove"> Aww. ! Looks like you
						don't have WRITE/CREATE access on Patients Data at this point of
						time. Please contact the Portal Administrator for obtaining the
						access. </i>
				</div>
				<%
					} else if (chk2!=null && chk2.equals("done")) {
						%>
				<div class='alert alert-info'>
					<i class="general foundicon-checkmark"> Successfully written the new Patient's data.
					<br><br>
				<form action='initiatePatientWrite' method=post>
					<input type=submit value='WRITE ANOTHER ONE' class='btn btn-success btn-small'/>
				</form></i>
				</div>
						<%
					} else if (chk2!=null && chk2.equals("fail")) {
						%>
				<div class='alert alert-error'>
					<i class="general foundicon-remove"> Aww. ! Something went
						wrong while writing new patient's data. Please try again later.</i>
				</div>
						<%
					}
					
					else {
				%>

				<div class='well'>Steps to create a new Patient Record</div>
				<ul class="nav nav-tabs">
					<li class="active"><a data-toggle="tab" href="#step1">Step
							1: Trustee</a></li>
					<li><a data-toggle="tab" href="#step2">Step 2: KDC</a></li>
					<li><a data-toggle="tab" href="#step3">Step 3: Application</a></li>
				</ul>

				<div class="tab-content">
					<div id='step1' class="tab-pane fade active in">
						Request a new Token from a Trustee.
						
						<br/><br/>

						
							<input type=submit class='btn btn-info'
								value='REQUEST TOKEN' id='requestToken'/>
						
							<div id ='tokenResult'></div>
					</div>


					<div id='step2' class="tab-pane fade">Request the Keys for
						Encryption/ Decryption from the KDCs. You would need to provide
						the Token obtained from Trustee to the KDC.
						
						<br/><br/>
						
						<form id='newk'>
							<label>
							Paste the Token		</label>
							<input type=text id='token' name='token' placeholder='Token obtained from Trustee'/>
							<br/><br/>
							<input type=submit class='btn btn-info'
								value='REQUEST KEYS' id='requestKey' />
						</form>					
						<div id ='keyResult'></div>
						
					</div>


					<div id='step3' class="tab-pane fade">Provide the details of
						the new Patient's record. The data will be encrypted using the
						Keys generated by KDC.
						
						<br/><br/>
						
						<form action='writePatient' id='newp' method=post>
							<label>Encryption Decryption ID</label>
							<input type=text name='encdecid' placeholder='ID obtained from KDC'/>
							<br/><br/>
							
							<label>Patient Name</label>
							<input type=text name='name' placeholder='Enter the patient name'/>
							<br/><br/>
							
							<label>Gender</label>
							<input type=text name='gender' placeholder='Enter patient gender'/>
							<br/><br/>
							
							<label>Mobile</label>
							<input type=text name='mobile' placeholder='Enter patient mobile'/>
							<br/><br/>
							
							<label>Age</label>
							<input type=text name='age' placeholder='Enter patient age'/>
							<br/><br/>
							
							
							<label>Address</label>
							<textarea name='address'></textarea>
							<br/><br/>
							
							<input type=reset class='btn btn-secondary'
								value='CLEAR DATA' />
								
							<input type=submit class='btn btn-info'
								value='WRITE PATIENT DATA' />
						</form>		
						
						
					</div>
				</div>


				<%
					}
				%>


				<div id="footerInnerSeparator"></div>
			</div>
		</div>

		<div id="footerOuterSeparator"></div>

		<%@include file="footer.jsp"%>
	</div>
	<br />
	<br />
	<br />
</body>
</html>

<script>
	$(document).ready(function() {
		
		$('#requestToken').click(function() {
			$.ajax({
				url : 'requestToken',
				success: function(data) {
					$('#requestToken').fadeOut();
					$('#tokenResult').html(data);
					$('#tokenResult').fadeIn();
				}
			});
		});
		
	

		$('#menu_pt').attr({
			'class' : 'dropdown active'
		})

		$('#newp').validate({
			rules : {
				'name' : 'required',
				'age' : 'required',
				'address' : 'required',
				'encdecid' : 'required',
				'mobile' : 'required',
				'gender' : 'required'
			},
			messages : {
				'name' : '* Name is a mandatory field',
				'age' : '* Age is a mandatory field',
				'address' : '* Address is a mandatory field',
				'encdecid' : '* This ID is a mandatory field. In case you dont have it, Please goto step 2 to request a new one',
				'mobile' : '* Mobile is a mandatory field',
				'gender' : '* Gender is a mandatory field'
			},
			submitHandler : function(form) {
				form.submit();
			}
		});
		
		$('#newk').validate({
			rules : {
				'token' : 'required'
			},
			messages : {
				'token' : '* Token is a mandatory field. In case you dont have it, Please goto step 1 to request a new one.'
			},
			submitHandler : function(form) {
				var token = $('#token').val();
				$.ajax({
					url : 'requestKey?token='+token,
					success: function(data) {
						$('#requestKey').fadeOut();
						$('#keyResult').html(data);
						$('#keyResult').fadeIn();
					}
				});

			}
		});
	});
</script>